### member list 불러오기
GET localhost:8080/api/members
Content-Type: application/json

### member 등록하기
POST localhost:8080/api/member
Content-Type: application/json

{
  "name": "이해든"
}
k
### Article 저장
POST localhost:8080/api/articles
Content-Type: application/json

{
  "title" : "make blog",
  "content" : "nothing content"
}

### Article 조회
GET localhost:8080/api/articles
Content-Type: application/json

### Article 단건 조회
GET localhost:8080/api/articles/2
Content-Type: application/json

### Article 단건 삭제
DELETE localhost:8080/api/articles/1

### Article 수정
PUT localhost:8080/api/articles/2
Content-Type: application/json

{
  "title": "only update title"
}


