
### member list 불러오기
GET localhost:8080/api/members
Content-Type: application/json

### member 등록하기
POST localhost:8080/api/member
Content-Type: application/json

{
  "name": "이해든"
}
k
### Article 저장
POST localhost:8080/api/articles
Content-Type: application/json

{
  "title" : "blog test",
  "content" : "yes"
}

### Article 조회
GET localhost:8080/api/articles
Content-Type: application/json

### Article 단건 조회
GET localhost:8080/api/articles/4
Content-Type: application/json

### Article 단건 삭제
DELETE localhost:8080/api/articles/1

### Article 수정
PUT localhost:8080/api/articles/2
Content-Type: application/json

{
  "title": "only update title"
}

### Article과 Comment 함께 조회
@Comment죄회할articleId = 4
GET localhost:8080/api/articles/{{Comment죄회할articleId}}/comment

### Comment 입력
@articleId = 6
POST localhost:8080/api/articles/{{articleId}}/comment
Content-Type: application/json

{
  "body": "6-1"
}

### Comment 단건 조회
@commentId= 8
GET localhost:8080/api/articles/comment/{{commentId}}


### Comment 수정
@수정commentid = 7
PUT localhost:8080/api/articles/comment/{{수정commentid}}
Content-Type: application/json

{
  "body": "4-3 update"
}

### Comment 삭제
@삭제id = 7
DELETE localhost:8080/api/articles/comment/{{삭제id}}

